# 使用 Alpine Linux 作为基础镜像
FROM  zhxgharbor.istarshine.com/dflow/centos7_rmqclient:3.6

# 安装 tzdata 包以支持时区配置
RUN yum install -y tzdata && \
    # 设置时区为 Asia/Shanghai
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    # 验证时区配置
    echo "当前时区:" && date +%Z

## 设置环境变量以支持中文 UTF-8 和时区
#ENV LANG=C.UTF-8 \
#    LC_ALL=C.UTF-8 \
#    TZ=Asia/Shanghai

# 安装Python依赖
RUN pip3.6 install --no-cache-dir \
    loguru \
    redis \
    ujson \
    pandas \
    pytz \
    -i https://pypi.tuna.tsinghua.edu.cn/simple/

RUN pip3.6 install actrie

# 设置工作目录
WORKDIR /app
COPY ../bak/研究获取职业数据.py /app/
COPY ../utils /app/utils
COPY ../config  /app/config
COPY ../output /app/output
COPY 职业kind.txt /app/职业kind.txt

# 创建日志目录
RUN mkdir -p /app/logs

WORKDIR /app
CMD ["python3.6","研究获取职业数据.py"]
