# 使用 CentOS 7 作为基础镜像
FROM zhxgharbor.istarshine.com/dflow/centos7_rmqclient:3.6

# 安装 glibc-common 以支持 locale 生成
RUN yum install -y tzdata && \
    # 设置时区为 Asia/Shanghai
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    # 验证时区配置
    echo "当前时区:" && date +%Z

RUN pip3.6 install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple/
# 设置环境变量以支持中文 UTF-8 和时区
ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    TZ=Asia/Shanghai

# 安装 Python 依赖
RUN pip3.6 install --no-cache-dir \
    loguru \
    requests \
    mysql-connector-python==8.0.6 \
    elasticsearch \
    ujson \
    redis \
    thrift==0.13.0 \
    pytz

RUN pip3.6 install pandas
RUN pip3.6 install openpyxl
RUN pip3.6 install xlrd

# 设置工作目录
WORKDIR /app

COPY user_profile/user_graph-master/utils /app/utils
COPY user_profile/user_graph-master/config  /app/config
COPY user_profile/user_graph-master/mqdata_to_mysql.py /app/
COPY user_profile/user_graph-master/final_stanterd.xlsx /app/


ENV env=beta

# 创建日志目录
RUN mkdir -p /app/logs

CMD ["python3.6", "mqdata_to_mysql.py"]